version: '3.8'

services:
  web:
    image: app-csharp:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" 
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    volumes:
      - ./Storage:/app/Storage
